### ISSUE TITLE
build error: A package named pekwm does not exist

### ISSUE THREAD

**Issue by LeSpocky** [WAGO/pfc-firmware-sdk-G2#6] opened 2023-03-29 11:44 UTC
Tried to build this BSP, but get the following error:

```
/mnt/data/adahl/src/pfc-firmware-sdk-G2/rules/post/dependencies-for-parallel-build.make:144: A package named pekwm does not exist
```

Seems to be due to a statement in *rules/post/dependencies-for-parallel-build.make* …

(Maybe those dependencies should be "fixed" by actually adding them in *rules/<pkg>.in* as `select` statements?)

**Comment by falk-werner** [comment] 2023-03-31 09:14
Thanks for the finding. It will be fixed along with the upcoming firmware 24 SDK.

This warning is issued because the pekwm (X11 window manager) package is not contained in PFC G2 firmware SDK. This package is part of the touch panel firmware and therefore mentioned as dependency for parallel build. The warning only complains about the missing package, it has no effect on the build itself.

**Comment by falk-werner** [comment] 2023-04-18 05:55
As mentioned before, the issue is fixed with firmware 24 SDK.

**Closed as completed by falk-werner** 2023-04-18 05:55 UTC
